### ISSUE TITLE
iThemes Security Pro

### ISSUE THREAD

**Issue by kzant** [passkeydeveloper/discussions#4]
### Service Name

iThemes Security Pro for WordPress

### Service URL

https:/www.ithemes.com/security/

### Terminology

- [X] Using passkey terminology

### Icon

- [ ] Using passkey icon

### Autofill - Web

- [X] Supported

### Autofill - Android

- [X] Supported

### Autofill - iOS

- [X] Supported

### Contact

- [X] I am

### Additional Information

iThemes Security Pro is a security plugin for WordPress sites that allows site owners to both use passkeys for login as well as offer passkeys to users for eCommerce, learning management implementations, and any other type of WordPress site. WordPress-driven sites account for 40% of major sites. The free version of iThemes Security does not offer passkeys, but it is used by over 1 million WordPress sites. iThemes Security Pro is the upgraded version and offers passkeys for WordPress. iThemes Security Pro is extremely affordable, and is a great tool for site owners looking to show their commitment to the future of authentication with passkeys.

**Comment by timcappalli** [comment]
added: https://github.com/passkeydeveloper/discussions/wiki/Known-Passkey-Support/e7819dad1d560597ac0041b7e20280ef4e32ef47
