### ISSUE TITLE
Best Buy support for passkeys

### ISSUE THREAD

**Issue by joostd** [passkeydeveloper/discussions#5]
### Service Name

Best Buy

### Service URL

https://www.bestbuy.com/

### Terminology

- [X] Using passkey terminology

### Icon

- [ ] Using passkey icon

### Autofill - Web

- [ ] Supported

### Autofill - Android

- [ ] Supported

### Autofill - iOS

- [ ] Supported

### Contact

- [ ] I am

### Additional Information

Some remarks:

- Passkey configuration: https://www.bestbuy.com/identity/accountSettings/page/webAuthnDetails
- `create()` doesn't allow you to select roaming authenticators (although `get()` does)
- Doesn't support macOS 13/Chrome 107 (generates an error message), however *does* support macOS 13/Edge 107.
- tested autofill on macOS 13/Safari 16 (not tested on Android and iOS).

More services listed here: https://passkeys.directory/

**Comment by timcappalli** [comment]
Best Buy does not support fully support passkeys. We will add them to the list once they do.

**Comment by joostd** [comment]
Ok, let’s close this one. 
For my understanding, what does full support entail? Having all the checkboxes marked, or simply support for discoverable credentials?

**Comment by timcappalli** [comment]
At a minimum, if the service has a button for signing in with a passkey, they should not be asking the user to enter a username on the subsequent screen.
