### ISSUE TITLE
www.corbado.com as new addition

### ISSUE THREAD

**Issue by vincentdelitz** [passkeydeveloper/discussions#6]
### Service Name

Corbado

### Service URL

www.corbado.com

### Terminology

- [ ] Using passkey terminology

### Icon

- [ ] Using passkey icon

### Autofill - Web

- [X] Supported

### Autofill - Android

- [ ] Supported

### Autofill - iOS

- [ ] Supported

### Contact

- [X] I am

### Additional Information

The new passkey icon will be added soon :)

**Comment by timcappalli** [comment]
added!
