### ISSUE TITLE
Add Hanko

### ISSUE THREAD

**Issue by FlxMgdnz** [passkeydeveloper/discussions#7]
### Service Name

Hanko

### Service URL

https://github.com/teamhanko/hanko

### Terminology

- [X] Using passkey terminology

### Icon

- [ ] Using passkey icon

### Autofill - Web

- [X] Supported

### Autofill - Android

- [X] Supported

### Autofill - iOS

- [X] Supported

### Contact

- [X] I am

### Additional Information

Self-hosted, open source

**Comment by timcappalli** [comment]
done! Also added Hanko Cloud
